### ISSUE TITLE
Update to PAT using Bot user

### ISSUE THREAD

**Issue by wderezin** [daringway/terraform-aws-account-setup#7]

**Comment by ksgriggs** [comment]
- Created personal access token for daringbot.
- Updated personal access token in terraform-aws-infrastructure secrets.

I gave the PAT the same permissions the original had and it should work.  This needs to be tested.

**Comment by wderezin** [comment]
I tested this and the access needed to be updated.   Check slack for discussion.

**Comment by ksgriggs** [comment]
We converted the PAT last week.
